//Title: Element.h
//Author: Jeremy Dixon
//Date: 2/18/2025
//Description: This is part of the DoodleGod Project in CMSC 202 @ UMBC

//Do not edit this file
//Do not create Element.cpp

#ifndef ELEMENT_H //Include/Header Guard
#define ELEMENT_H //Include/Header Guard

#include <string>
#include <iostream>
#include <cstdlib>

using namespace std;

// Name: Element struct
// Desc - Used to store data about elements.
// Elements - Air, Earth, Fire, and are prime and do not have required elements
//            User starts with Air, Earth, Fire, and Water elements
struct Element{
public:
  string m_name; //Name of the element
  string m_element1; //Required element 1 to create 
  string m_element2; //Required element 2 to create
  Element(){} //Default constructor
  Element(string name, string element1, string element2){
    m_name = name; //Name of this element
    m_element1 = element1; //Name of first required element to create
    m_element2 = element2; //Name of second required element to create
  }
};

#endif
